# Generated by Django 4.2.15 on 2024-09-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_specifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
