# Generated by Django 4.2.15 on 2024-09-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_specifications", "0003_alter_brand_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
